# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ZeeguuAPI' do
	pod 'SwiftyJSON', :git => "https://github.com/SwiftyJSON/SwiftyJSON.git"
end

target 'ZeeguuAPITests' do
	pod 'SwiftyJSON', :git => "https://github.com/SwiftyJSON/SwiftyJSON.git"
end

